[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/route"
  to = "/.netlify/functions/route"
  status = 200
  force = true

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200
  force = true
